# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches:
    - dev
    - release
    - 'hotfix-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build npm files
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npm --no-git-tag-version --allow-same-version version $(<VERSION)
    - run: npm run prepublishOnly
    #- name: Render Markdown into HTML
    #  uses: ZacJW/markdown-html-action@1.1.1
    #  with:
    #    input_files: README.md
    #    output_files: index.html
    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: CI npm build
